const ROLES = {
  ADMIN: 'admin',
  ADMINISTRATOR: 'administrator',
  ADMINISTRATIVE_OFFICER: 'administrative-officer',
  AGE_GROUP_SUPERVISOR: 'age-group-supervisor',
  SPORTS_DIRECTOR: 'sports-director',
  EXECUTIVE_DIRECTOR: 'executive-director',
  SECRETARY: 'secretary',
  SPORTS_ADMINISTRATOR: 'sports-administrator',
  PLAYER: 'player',
  COACH: 'coach',
  CLUB: 'club',
  SPECIALIST: 'specialist',
  TEAM: 'team',
  APPLICANT: 'applicant',
  JOB_PUBLISHER: 'job-publisher'
};

const PERMISSIONS = {
  // System & Settings
  MANAGE_SYSTEM: 'manage_system',
  VIEW_LOGS: 'view_logs',
  MANAGE_SETTINGS: 'manage_settings',
  
  // User Management
  MANAGE_USERS: 'manage_users',
  VIEW_USERS: 'view_users',
  BLOCK_USERS: 'block_users',
  DELETE_USERS: 'delete_users',
  
  // Content Management
  MANAGE_CONTENT: 'manage_content', // Articles, announcements
  
  // Sports Management
  MANAGE_PROGRAMS: 'manage_programs',
  VIEW_PROGRAMS: 'view_programs',
  MANAGE_COACHES: 'manage_coaches',
  VIEW_COACH_PERFORMANCE: 'view_coach_performance',
  MANAGE_COACH_EVALUATIONS: 'manage_coach_evaluations',
  MANAGE_ATHLETES: 'manage_athletes',
  VIEW_ATHLETES: 'view_athletes',
  MANAGE_RECRUITMENT: 'manage_recruitment',
  
  // Analytics
  VIEW_ANALYTICS: 'view_analytics',
  VIEW_TRAINING_ANALYTICS: 'view_training_analytics',
  
  // Age Groups
  MANAGE_AGE_GROUPS: 'manage_age_groups',
  
  // Administrative
  APPROVE_REQUESTS: 'approve_requests',
  MANAGE_DOCUMENTS: 'manage_documents',
  MANAGE_MEETINGS: 'manage_meetings',

  // Strategy & Partnerships
  MANAGE_STRATEGY: 'manage_strategy', // KPIs, Initiatives
  MANAGE_PARTNERSHIPS: 'manage_partnerships',
  VIEW_FINANCIALS: 'view_financials',

  // Job Management
  VIEW_JOBS: 'view_jobs',
  APPLY_TO_JOBS: 'apply_to_jobs',
  MANAGE_JOB_APPLICATIONS: 'manage_job_applications',
  PUBLISH_JOBS: 'publish_jobs',
  MANAGE_OWN_JOBS: 'manage_own_jobs',
  VIEW_JOB_APPLICATIONS: 'view_job_applications',

  // Club-specific permissions
  MANAGE_OWN_CLUB_PROFILE: 'manage_own_club_profile',
  VIEW_OWN_CLUB_PROFILE: 'view_own_club_profile',
  MANAGE_CLUB_MEMBERS: 'manage_club_members',
  VIEW_CLUB_MEMBERS: 'view_club_members',
  APPROVE_MEMBERSHIP_REQUESTS: 'approve_membership_requests',
  MANAGE_CLUB_TEAMS: 'manage_club_teams',
  VIEW_CLUB_TEAMS: 'view_club_teams',
  MANAGE_CLUB_EVENTS: 'manage_club_events',
  VIEW_CLUB_EVENTS: 'view_club_events',
  MANAGE_CLUB_FACILITIES: 'manage_club_facilities',
  VIEW_CLUB_BOOKINGS: 'view_club_bookings',
  APPROVE_BOOKINGS: 'approve_bookings',
  MANAGE_CLUB_MEDIA: 'manage_club_media',
  VIEW_CLUB_ANALYTICS: 'view_club_analytics',
  VIEW_CLUB_STATS: 'view_club_stats',
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.EXECUTIVE_DIRECTOR]: [
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_TRAINING_ANALYTICS,
    PERMISSIONS.VIEW_PROGRAMS,
    PERMISSIONS.VIEW_COACH_PERFORMANCE,
    PERMISSIONS.VIEW_ATHLETES,
    PERMISSIONS.APPROVE_REQUESTS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_MEETINGS,
    PERMISSIONS.MANAGE_STRATEGY,
    PERMISSIONS.MANAGE_PARTNERSHIPS,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.SPORTS_DIRECTOR]: [
    PERMISSIONS.MANAGE_PROGRAMS,
    PERMISSIONS.MANAGE_COACHES,
    PERMISSIONS.VIEW_COACH_PERFORMANCE,
    PERMISSIONS.MANAGE_COACH_EVALUATIONS,
    PERMISSIONS.MANAGE_ATHLETES,
    PERMISSIONS.VIEW_TRAINING_ANALYTICS,
    PERMISSIONS.MANAGE_RECRUITMENT,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.AGE_GROUP_SUPERVISOR]: [
    PERMISSIONS.MANAGE_AGE_GROUPS,
    PERMISSIONS.VIEW_ATHLETES,
    PERMISSIONS.VIEW_COACH_PERFORMANCE,
    PERMISSIONS.MANAGE_COACH_EVALUATIONS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.ADMINISTRATOR]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_DOCUMENTS
  ],
  
  [ROLES.ADMINISTRATIVE_OFFICER]: [
    PERMISSIONS.MANAGE_DOCUMENTS,
    PERMISSIONS.MANAGE_MEETINGS,
    PERMISSIONS.VIEW_USERS
  ],

  [ROLES.SECRETARY]: [
    PERMISSIONS.MANAGE_MEETINGS,
    PERMISSIONS.MANAGE_DOCUMENTS
  ],
  
  [ROLES.SPORTS_ADMINISTRATOR]: [
    PERMISSIONS.MANAGE_PROGRAMS,
    PERMISSIONS.MANAGE_RECRUITMENT
  ],

  [ROLES.APPLICANT]: [
    PERMISSIONS.VIEW_JOBS,
    PERMISSIONS.APPLY_TO_JOBS,
    PERMISSIONS.MANAGE_JOB_APPLICATIONS
  ],

  [ROLES.JOB_PUBLISHER]: [
    PERMISSIONS.PUBLISH_JOBS,
    PERMISSIONS.MANAGE_OWN_JOBS,
    PERMISSIONS.VIEW_JOB_APPLICATIONS,
    PERMISSIONS.VIEW_JOBS
  ],

  [ROLES.CLUB]: [
    // Profile Management
    PERMISSIONS.MANAGE_OWN_CLUB_PROFILE,
    PERMISSIONS.VIEW_OWN_CLUB_PROFILE,
    
    // Member Management
    PERMISSIONS.MANAGE_CLUB_MEMBERS,
    PERMISSIONS.VIEW_CLUB_MEMBERS,
    PERMISSIONS.APPROVE_MEMBERSHIP_REQUESTS,
    
    // Team Management
    PERMISSIONS.MANAGE_CLUB_TEAMS,
    PERMISSIONS.VIEW_CLUB_TEAMS,
    
    // Job & Recruitment
    PERMISSIONS.PUBLISH_JOBS,
    PERMISSIONS.MANAGE_OWN_JOBS,
    PERMISSIONS.VIEW_JOB_APPLICATIONS,
    PERMISSIONS.MANAGE_RECRUITMENT,
    
    // Events & Activities
    PERMISSIONS.MANAGE_CLUB_EVENTS,
    PERMISSIONS.VIEW_CLUB_EVENTS,
    
    // Facilities & Bookings
    PERMISSIONS.MANAGE_CLUB_FACILITIES,
    PERMISSIONS.VIEW_CLUB_BOOKINGS,
    PERMISSIONS.APPROVE_BOOKINGS,
    
    // Media & Gallery
    PERMISSIONS.MANAGE_CLUB_MEDIA,
    
    // Analytics
    PERMISSIONS.VIEW_CLUB_ANALYTICS,
    PERMISSIONS.VIEW_CLUB_STATS
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
